apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample-chart.fullname" . }}
spec:
  selector:
    app: {{ include "sample-chart.name" . }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
