replicaCount: 3
image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  port: 80
ingress:
  enabled: true
  hosts:
    - host: sample.local
      paths:
        - path: /
          pathType: Prefix
resources: {}